# Generated by Django 2.1.7 on 2019-04-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190415_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gamesPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='deviceTheme',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='playerTheme',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
