# Generated by Django 2.1.7 on 2019-04-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190416_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='deviceTheme',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='playerTheme',
            field=models.IntegerField(default=1),
        ),
    ]
