# Generated by Django 2.1.7 on 2019-04-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190416_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='deviceTheme',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gamesPlayed',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
