# Generated by Django 2.1.7 on 2019-04-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190417_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='averagePoints',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='totalPoints',
            field=models.IntegerField(default=0),
        ),
    ]
