# Generated by Django 2.1.7 on 2019-04-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190417_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
