# Generated by Django 2.1.7 on 2019-04-17 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_userinfo_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='updatedTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 23, 23, 40, 585856)),
        ),
    ]
