# Generated by Django 2.1.7 on 2019-04-17 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20190417_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='updatedTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
