# Generated by Django 2.1.7 on 2019-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_userinfo_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
